### ISSUE TITLE
Inbound Channels

### ISSUE THREAD

**Issue by 0xBEEFCAF3** [chaincase-app/nolooking#40]
### What we're building
Open inbound channels when requested. Capacity should be dynamic (max is based on total liquidity and/or third-party liquidity provider).

### UI Updates
We need to provide an optional set of input fields. Capacity should be denominated in sats. A check box should be provided to opt out of this service. 

### Changes to the PSBT
1) Increase the bip21 amount by however much the user requests for inbound capacity
2) Create a new output on the original PSBT that spends to an on-chain address  

#### LnBig
LnBig offers a ws and RESTful interface.
Routes can be found at https://github.com/LNBIG-COM/lnbig-server/blob/new_open_channel/app.js#L31-L41
In return for requesting a channel, lnBig returns as HODL invoice, after an on-chain payment, the invoice will be completed and a channel will be opened. 

Cons: No support, no API docs, potential language barrier, paying a HODL invoice is not as easy as an onchain payment.
Pros: No need to host infra, or take on additional operational costs 

#### Clone Zero-fee
The no-looking client would POST an inbound channel open to the "no-looking" server. The server creates a BTCPay invoice. And creates an DB entry mapping on-chain address to lnaddress. Then listens for BTCPay webhooks. After tx is paid (0-conf), the server will call to voltage to open a channel with capacity provided by the user. 

The cons 
* Provide mainnet inbound liquidity 
* Support BTCPay infrastructure  on voltage
* Operational cost and burden
The pro is that it would be fairly easy to implement

### Deezy
Docs: https://docs.deezy.io/#tag/Swap-(BTC-to-LN)
Exactly what we are looking for. Get an on-chain address after registering for the API. 

Cons: They don't seem to handle payment/routing failures (> 0 probability) 
Pros: No need to host new infra.

**Comment by DanGould** [comment]
YES! Now we're talking.

Does deezy open a direct channel? Looks they pay an invoice. Also, it's custodial and there's some trust involved. The discord is active

**Comment by 0xBEEFCAF3** [comment]
> Does deezy open a direct channel?

Asked a question in the discord. Will update this thread with the response.

**Comment by 0xBEEFCAF3** [comment]
>currently it does not automatically open a channel, it just tries to pay via LN

From the Deezy team

**Comment by 0xBEEFCAF3** [comment]
We could open an channel with deezy upon user confirmation. Then in a later step they could swap.

**Comment by DanGould** [comment]
Could also find a suitable [Magma](https://amboss.space/magma?type=channel) order and then use a non-custodial atomic swap from [Boltz](https://boltz.exchange/) to pay for it

**Comment by 0xBEEFCAF3** [comment]
Also a potential path. I think reliance on fewer 3rd parties > more.

**Comment by 0xBEEFCAF3** [comment]
### Phases for implementing this 
1) Add a check box to opt in for default channels + channels that can swap inbound liquidity.
2) New UI to swap onchain funds to inbound liquidity. Essentially a front end for https://docs.deezy.io/#tag/Swap-(BTC-to-LN)/operation/createSource
3) Stretch goal some dashboard UI would be useful here. Miniamlly show pending and open channels with cap

**Comment by DanGould** [comment]
Wouldn't using swap require you to have spend the whole amount of an inbound chanel? I think that's way more than the going rate otherwise using loop/magma/liquidity ads

**Comment by 0xBEEFCAF3** [comment]
>Wouldn't using swap require you to spend the whole amount of an inbound channel?

After you receive the inbound capacity?

**Comment by 0xBEEFCAF3** [comment]
Another semi-trusted solution: https://ln2me.com/

**Comment by 0xBEEFCAF3** [comment]
Using Thor + Bitrefill https://www.bitrefill.com/buy/lightning-channel/
What is Thor: 
>This service will let anyone get an empty Lightning channel opened to them from Bitrefill's node on the Lightning network. Now anyone can pay for, or gift, the ability to have a channel opened to a Lightning wallet, allowing them to receive payments over Lightning at any time.

**Comment by 0xBEEFCAF3** [comment]
Ya'lls is another potential soluition. However, you need to pay an invoice to get your inbound not an onchain addresshttps://yalls.org/about/

**Comment by DanGould** [comment]
[Blocktank](https://blocktank.to/) is live and their api returns a channel quote with an on chain btc_address https://synonym.readme.io/reference/buychannel. Seems like a straight up API to go 0 to 1 on this problem.

**Comment by 0xBEEFCAF3** [comment]
I dont know how I missed Voltage flow: https://api-docs.voltage.cloud/#tag/Flow/paths/~1flow~1create/post

I am currently favoring this solution. Less third parties dependencies the better

**Comment by nickfarrow** [comment]
Looks like Voltage Flow will only let us use API to open nodes to ourselves, can't specify a node.?. Shame

**Comment by 0xBEEFCAF3** [comment]
My impression was that Flow lets you buy a sidecar channel on the behalf of someone else.

**Comment by DanGould** [comment]
> Looks like Voltage Flow will only let us use API to open nodes to ourselves, can't specify a node?

Curious what the problem with flow is? Nolooking has full admin access to a node. Nolooking would be purchasing a node to itself.

**Comment by DanGould** [comment]
![image](https://user-images.githubusercontent.com/8525467/202336698-2b2ff753-c66b-4aae-92b7-c4da32907198.png)

**Comment by DanGould** [comment]
closed by #65
