### ISSUE TITLE
Add cache headers for static assets

### ISSUE THREAD

**Issue by nickfarrow** [chaincase-app/nolooking#43]
@nevets963 noted in our app submission:
> There are no cache (Cache-Control) headers set for your static assets. I tested nolooking on a server on the other side of the earth, so we could improve (repeat) load performance a little bit with caching here. This will also help with access over Tor (which is pretty slow).

**Comment by DanGould** [comment]
closed by #44. If you use a keyword from these instead of "Addresses" it'll close the associated issue automatically

>     close
>     closes
>     closed
>     fix
>     fixes
>     fixed
>     resolve
>     resolves
>     resolved

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
