### ISSUE TITLE
Display payjoin errors within the UI

### ISSUE THREAD

**Issue by nickfarrow** [chaincase-app/nolooking#50]
It would be great for UX and testing if we could see errors within the UI.

Usually this would not be so important for testing, since you can just read the logs. However fetching the logs on umbrel is very slow and makes for a bad experience when payjoins are failing.

A user should be able to know immediately if a node rejected a channel for <reason>, e.g. too small.

**Comment by DanGould** [comment]
I think it makes the most sense to keep the errors via Push API (Service Workers), but that requires https so I'm not sure it's going to work in the umbrel environment

**Comment by 0xBEEFCAF3** [comment]
Can we use web sockets or worse-case polling? The first thing the webapp does is acquire pj state.

**Comment by DanGould** [comment]
I think I was thinking about this all wrong. payjoin receiver errors should be sent back to the sender which is done now in #57

**Comment by DanGould** [comment]
closed by #93
