### ISSUE TITLE
Autoload recommended channels

### ISSUE THREAD

**Issue by 0xBEEFCAF3** [chaincase-app/nolooking#90]
On second thought, we may want this to try to auto load but have 3 states (button, loading, output) where we start on loading, but if the browser has js disabled then we go to button & form submission. Perhaps overkill

_Originally posted by @DanGould in https://github.com/chaincase-app/nolooking/pull/71#discussion_r1028406235_

**Comment by DanGould** [comment]
this might be better with server side rendereing. On the index route have the server make the call to deliver channels recommendations instead of the js client

**Comment by DanGould** [comment]
recommendation errors removed for now because of the results of demand experiments
