### ISSUE TITLE
`impl std::error::Error` on lsp and recommended errors 

### ISSUE THREAD

**Issue by 0xBEEFCAF3** [chaincase-app/nolooking#91]
I'm realizing neither error `impl std::error::Error` here or in lsp.rs. So it's not a regression, but should be implemented on both of these types going forward.

_Originally posted by @DanGould in https://github.com/chaincase-app/nolooking/issues/71#issuecomment-1322814834_

**Comment by DanGould** [comment]
LSP & recommendation engine features removed as a result of demand testing
